base: '%env("PROJECT_BASE_URL")%'
errorHandling:
  -
    errorCode: 404
    errorHandler: Fluid
    errorFluidTemplate: 'EXT:bike_provider/Resources/Private/Templates/Error.html'
    errorFluidTemplatesRootPath: ''
    errorFluidLayoutsRootPath: ''
    errorFluidPartialsRootPath: ''
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: English
    hreflang: de-de
    direction: ltr
    flag: de
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
routeEnhancers:
  api:
    type: Extbase
    extension: Pepebike
    plugin: Api
    routes:
      - routePath: '/{object}'
        _controller: 'Json::list'
      - routePath: '/{object}/{id}'
        _controller: 'Json::list'
    defaultController: 'Json::list'