base: '%env("PROJECT_BASE_URL")%'
errorHandling:
  -
    errorCode: 404
    errorHandler: Fluid
    errorFluidTemplate: 'EXT:bike_provider/Resources/Private/Templates/Error.html'
    errorFluidTemplatesRootPath: ''
    errorFluidLayoutsRootPath: ''
    errorFluidPartialsRootPath: ''
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-de
    direction: ltr
    flag: de
    websiteTitle: 'German Site'
  -
    title: English
    enabled: true
    languageId: 1
    base: /en
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: en-us-gb
    websiteTitle: 'English Site'
    fallbackType: strict
    fallbacks: ''
rootPageId: 1
routeEnhancers:
  api:
    type: Extbase
    extension: Pepebike
    plugin: Api
    routes:
      -
        routePath: '/{object}'
        _controller: 'Json::list'
      -
        routePath: '/{object}/{id}'
        _controller: 'Json::list'
    defaultController: 'Json::list'
websiteTitle: ''
