base: '%env("PROJECT_BASE_URL")%'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: English
    hreflang: de-de
    direction: ltr
    flag: de
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
