services:
  Luat\PepeBike\Command\SendEmailCommand:
    tags:
      - name: 'console.command'
        command: 'pepebike:send_email'
        description: 'Sends Email'
        schedulable: true
        hidden: false